services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transcriptions-backend
    environment:
      AppEnvironment: live
    ports:
      - "8000:80"
    volumes:
      - ./backend:/app:z
    networks:
      - transcription-shared

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: transcriptions-frontend
    environment:
      AppEnvironment: live
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:z
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next
    depends_on:
      - backend

networks:
  transcription-shared:
    external: true

volumes:
  frontend_node_modules:
  frontend_next:
